version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  groups:
    k8s.io:
      patterns:
        - "k8s.io/*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
