# .goreleaser.yml
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

before:
  hooks:
    - go mod download

builds:
  - binary: oc-console
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w

release:
  github:
    owner: cblecker
    name: oc-console
  prerelease: auto
