# .goreleaser.yml
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  - id: oc-console-main
    binary: oc-console
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
    hooks:
      post:
      - upx "{{ .Path }}"
  - id: oc-console-winarm64
    binary: oc-console
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
release:
  github:
    owner: cblecker
    name: oc-console
  prerelease: auto
