on: pull_request
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      uses: actions-contrib/golangci-lint@master
      env:
        GOPROXY: https://proxy.golang.org
      with:
        args: run
